// <auto-generated />
using Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Data.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    partial class ApplicationDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "7.0.9");

            modelBuilder.Entity("Models.Message", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("BankIdentifier")
                        .HasColumnType("TEXT");

                    b.Property<string>("CHK")
                        .HasColumnType("TEXT");

                    b.Property<string>("MAC")
                        .HasColumnType("TEXT");

                    b.Property<string>("Tag15_SendersReference")
                        .HasColumnType("TEXT");

                    b.Property<string>("Tag20_TransactionReferenceNumber")
                        .HasColumnType("TEXT");

                    b.Property<string>("Tag21_RelatedReference")
                        .HasColumnType("TEXT");

                    b.Property<string>("Tag22_TypeOfOperation")
                        .HasColumnType("TEXT");

                    b.Property<string>("Tag23_FurtherIndetification")
                        .HasColumnType("TEXT");

                    b.Property<string>("Tag25_ProcessingFrequency")
                        .HasColumnType("TEXT");

                    b.Property<string>("Tag26_NumberOfAvailableTenors")
                        .HasColumnType("TEXT");

                    b.Property<string>("Tag27_SequenceOfTotal")
                        .HasColumnType("TEXT");

                    b.Property<string>("Tag30_Date")
                        .HasColumnType("TEXT");

                    b.Property<string>("Tag31_DateTimePeriod")
                        .HasColumnType("TEXT");

                    b.Property<string>("Tag32_CurrencyAmount")
                        .HasColumnType("TEXT");

                    b.Property<string>("Tag33_CurrencyOriginalOrderedAmount")
                        .HasColumnType("TEXT");

                    b.Property<string>("Tag34_Percentage")
                        .HasColumnType("TEXT");

                    b.Property<string>("Tag35_SequenceOfFormOfDocumentary")
                        .HasColumnType("TEXT");

                    b.Property<string>("Tag36_DescriptionOfGoodsAndServices")
                        .HasColumnType("TEXT");

                    b.Property<string>("Tag37_DocumentsRequired")
                        .HasColumnType("TEXT");

                    b.Property<string>("Tag39_PercentageCreditAmountTolerance")
                        .HasColumnType("TEXT");

                    b.Property<string>("Tag40_FormOfPresentation")
                        .HasColumnType("TEXT");

                    b.Property<string>("Tag41_AvailableWith")
                        .HasColumnType("TEXT");

                    b.Property<string>("Tag42_DraftsAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Tag43_Shipments")
                        .HasColumnType("TEXT");

                    b.Property<string>("Tag44_PlaceOfTakingInCharge")
                        .HasColumnType("TEXT");

                    b.Property<string>("Tag45_DescriptionOfGoodsOrServices")
                        .HasColumnType("TEXT");

                    b.Property<string>("Tag46_DocumentsRequired")
                        .HasColumnType("TEXT");

                    b.Property<string>("Tag47_AdditionalConditions")
                        .HasColumnType("TEXT");

                    b.Property<string>("Tag48_PeriodFroPresentation")
                        .HasColumnType("TEXT");

                    b.Property<string>("Tag49_ConfirmationInstructions")
                        .HasColumnType("TEXT");

                    b.Property<string>("Tag50_Applicant")
                        .HasColumnType("TEXT");

                    b.Property<string>("Tag51_ApplicantBank")
                        .HasColumnType("TEXT");

                    b.Property<string>("Tag52_IssuingBank")
                        .HasColumnType("TEXT");

                    b.Property<string>("Tag53_ReimbursingBank")
                        .HasColumnType("TEXT");

                    b.Property<string>("Tag54_AdvisingBank")
                        .HasColumnType("TEXT");

                    b.Property<string>("Tag55_SecondAdvisingBank")
                        .HasColumnType("TEXT");

                    b.Property<string>("Tag56_IntermediaryBank")
                        .HasColumnType("TEXT");

                    b.Property<string>("Tag57_AccountWithInstitution")
                        .HasColumnType("TEXT");

                    b.Property<string>("Tag58_Beneficiary")
                        .HasColumnType("TEXT");

                    b.Property<string>("Tag59_BeneficiaryBank")
                        .HasColumnType("TEXT");

                    b.Property<string>("Tag70_RemittanceInformation")
                        .HasColumnType("TEXT");

                    b.Property<string>("Tag71_Reimbursement")
                        .HasColumnType("TEXT");

                    b.Property<string>("Tag72_SenderToReceiverInformation")
                        .HasColumnType("TEXT");

                    b.Property<string>("Tag73_ChargeDetails")
                        .HasColumnType("TEXT");

                    b.Property<string>("Tag74_SendersCharges")
                        .HasColumnType("TEXT");

                    b.Property<string>("Tag75_InstructionToPayingAcceptingNegotiatingBank")
                        .HasColumnType("TEXT");

                    b.Property<string>("Tag79_Narrative")
                        .HasColumnType("TEXT");

                    b.Property<string>("Tag80_InstructionsToTheBeneficiarysBank")
                        .HasColumnType("TEXT");

                    b.Property<string>("Tag82_NIntermediaryBankCharges")
                        .HasColumnType("TEXT");

                    b.Property<string>("Tag83_ReimbursingBankCharges")
                        .HasColumnType("TEXT");

                    b.Property<string>("Tag84_AdviseThroughBankCharges")
                        .HasColumnType("TEXT");

                    b.Property<string>("Tag85_SecondAdvisingBankCharges")
                        .HasColumnType("TEXT");

                    b.Property<string>("TypeAndReference")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Messages");
                });
#pragma warning restore 612, 618
        }
    }
}
